### ISSUE TITLE
Please upgrade peerdependencies

### ISSUE THREAD

**Issue by maurice85** [Gaiidenn/angular-material-gesture#3]
I am using angular 13 with @angular/cdk 13.1.1 but angular-material-gesture is still looking for version 11.2.11 which results in an error. I don't want to use --force to install this dependency. Could you please upgrade the peerDependency list?

**Comment by Gaiidenn** [comment]
I will try to look at it as soon as I've got the time. I don't know if the library is compatible with angular 13 as it is, but as a workaround you can try some tsconfig parameters to overwrite subdependencies.

```
  "dependencies": {
   "angular-material-gesture": "~1.05"
    "@angular/core": "~4.6.2",
    ...
  },
  "overrides": {
    angular-material-gesture": {
      "@angular/core": "$@angular/core"
    }
  }
```

**Comment by Gaiidenn** [comment]
The library has now been updated and published for every angular version => you should now be able to install it again, without any dependency issue (since you are using angular 13, the @angular-material-gesture/mat-tab-group@1.2.0 should match your local deps).
